{% set version = "1.2.0" %}

package:
  name: hydride
  version: {{ version }}

source:
  url: https://github.com/biotite-dev/hydride/archive/v{{ version }}.tar.gz
  sha256: 945ec7c734665586ed577e63537b4a83646e446034f2e3fcd747f7f9b1d9d424

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py < 310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >=2.0                            # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
  host:
    - python
    - pip
    - setuptools >=0.30
    - wheel >=0.30
    - cython >=3.0
    - numpy >=2.0
    - msgpack-python
    - biotite >=1.0
  run:
    - python
    - numpy >=1.26
    - biotite >=1.0

test:
  source_files:
    - tests/
  requires:
    - pytest
  commands:
    - pytest --ignore tests/test_cli.py

about:
  home: https://hydride.biotite-python.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A software and library for adding hydrogen atoms to molecular models
  doc_url: https://hydride.biotite-python.org/
  dev_url: https://github.com/biotite-dev/hydride

extra:
  recipe-maintainers:
    - padix-key
