{% set version = "1.2.0" %}
{% set number = "0" %}
{% set sha256 = "945ec7c734665586ed577e63537b4a83646e446034f2e3fcd747f7f9b1d9d424" %}

package:
  name: hydride
  version: {{ version }}

source:
  url: https://github.com/biotite-dev/hydride/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ number }}
  script: {{ PYTHON }} -m pip install . --no-use-pep517 --no-deps --ignore-installed -vv
  skip: true  # [py < 38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - biotite                                # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools >=30.0
    - wheel >=0.30
    - cython >=0.29
    - numpy
    - msgpack-python
    - biotite >=0.28
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - biotite >=0.28

test:
  source_files:
    - tests/
  requires:
    - pytest
  commands:
    - pytest --ignore tests/test_cli.py

about:
  home: https://hydride.biotite-python.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A software and library for adding hydrogen atoms to molecular models
  doc_url: https://hydride.biotite-python.org/
  dev_url: https://github.com/biotite-dev/hydride

extra:
  recipe-maintainers:
    - padix-key
